/**
 * Shared TypeScript types for OPC Console.
 *
 * These mirror the 11 tables defined in supabase/migrations/0001_init.sql.
 * The `Database` type is intentionally lightweight (not generated by the
 * Supabase CLI) so the app builds with zero external state. If you later run
 * `supabase gen types`, you can swap this out — but keep the named row types
 * (`Workspace`, `Task`, ...) exported, since feature code imports them.
 */

// ---------------------------------------------------------------------------
// Enums / unions
// ---------------------------------------------------------------------------

export type SignalStatus = "new" | "triaged" | "archived"
export type TaskStatus = "open" | "doing" | "done"
export type AgentRunStatus = "pending" | "running" | "done" | "error"
export type MemberRole = "owner" | "admin" | "member"

// ---------------------------------------------------------------------------
// Row types (one per table)
// ---------------------------------------------------------------------------

export interface Workspace {
  id: string
  name: string | null
  created_at: string
}

export interface WorkspaceMember {
  workspace_id: string
  user_id: string
  role: string
  created_at: string
}

export interface Business {
  id: string
  workspace_id: string
  name: string | null
  kind: string | null
  created_at: string
}

export interface Signal {
  id: string
  workspace_id: string
  business_id: string | null
  source: string | null
  title: string | null
  body: string | null
  status: SignalStatus
  external_ref: string | null
  created_at: string
}

export interface Task {
  id: string
  workspace_id: string
  business_id: string | null
  title: string | null
  notes: string | null
  status: TaskStatus
  due_at: string | null
  priority: number
  created_at: string
}

export interface Obligation {
  id: string
  workspace_id: string
  business_id: string | null
  title: string | null
  kind: string | null
  recur_rule: string | null
  next_due_at: string | null
  lead_days: number
  last_done_at: string | null
  created_at: string
}

export interface Decision {
  id: string
  workspace_id: string
  business_id: string | null
  title: string | null
  body: string | null
  decided_at: string
  created_at: string
}

export interface WorkspaceSettings {
  workspace_id: string
  ai_provider: string | null
  ai_api_key: string | null
  created_at: string
}

export interface Brief {
  id: string
  workspace_id: string
  content: string | null
  for_date: string | null
  created_at: string
}

export interface Agent {
  id: string
  workspace_id: string
  name: string | null
  system_prompt: string | null
  model: string | null
  created_at: string
}

export interface AgentRun {
  id: string
  workspace_id: string
  agent_id: string
  input: string | null
  output: string | null
  status: string
  created_at: string
}

// ---------------------------------------------------------------------------
// Supabase Database shape (supabase-js generic).
//
// IMPORTANT: each table's Row / Insert / Update MUST be written as inline
// object-type literals (no generic aliases, no `Partial<Row>`, no references
// to the named interfaces above). supabase-js resolves the table types through
// deeply nested conditional/indexed types inside `from()`; when a table member
// is an aliased or utility type rather than a fresh object-type literal, the
// resolution collapses to `never` and `.insert()` / `.select()` lose their
// types (you get errors like "'workspace_id' does not exist in type 'never[]'").
// This mirrors the output of `supabase gen types typescript`, which inlines
// everything for exactly this reason. Keep it inlined.
// ---------------------------------------------------------------------------

export interface Database {
  public: {
    Tables: {
      workspaces: {
        Row: { id: string; name: string | null; created_at: string }
        Insert: { id?: string; name?: string | null; created_at?: string }
        Update: { id?: string; name?: string | null; created_at?: string }
        Relationships: []
      }
      workspace_members: {
        Row: { workspace_id: string; user_id: string; role: string; created_at: string }
        Insert: { workspace_id: string; user_id: string; role?: string; created_at?: string }
        Update: { workspace_id?: string; user_id?: string; role?: string; created_at?: string }
        Relationships: []
      }
      businesses: {
        Row: { id: string; workspace_id: string; name: string | null; kind: string | null; created_at: string }
        Insert: { id?: string; workspace_id: string; name?: string | null; kind?: string | null; created_at?: string }
        Update: { id?: string; workspace_id?: string; name?: string | null; kind?: string | null; created_at?: string }
        Relationships: []
      }
      signals: {
        Row: {
          id: string
          workspace_id: string
          business_id: string | null
          source: string | null
          title: string | null
          body: string | null
          status: "new" | "triaged" | "archived"
          external_ref: string | null
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          business_id?: string | null
          source?: string | null
          title?: string | null
          body?: string | null
          status?: string
          external_ref?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          business_id?: string | null
          source?: string | null
          title?: string | null
          body?: string | null
          status?: string
          external_ref?: string | null
          created_at?: string
        }
        Relationships: []
      }
      tasks: {
        Row: {
          id: string
          workspace_id: string
          business_id: string | null
          title: string | null
          notes: string | null
          status: "open" | "doing" | "done"
          due_at: string | null
          priority: number
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          business_id?: string | null
          title?: string | null
          notes?: string | null
          status?: string
          due_at?: string | null
          priority?: number
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          business_id?: string | null
          title?: string | null
          notes?: string | null
          status?: string
          due_at?: string | null
          priority?: number
          created_at?: string
        }
        Relationships: []
      }
      obligations: {
        Row: {
          id: string
          workspace_id: string
          business_id: string | null
          title: string | null
          kind: string | null
          recur_rule: string | null
          next_due_at: string | null
          lead_days: number
          last_done_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          business_id?: string | null
          title?: string | null
          kind?: string | null
          recur_rule?: string | null
          next_due_at?: string | null
          lead_days?: number
          last_done_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          business_id?: string | null
          title?: string | null
          kind?: string | null
          recur_rule?: string | null
          next_due_at?: string | null
          lead_days?: number
          last_done_at?: string | null
          created_at?: string
        }
        Relationships: []
      }
      decisions: {
        Row: {
          id: string
          workspace_id: string
          business_id: string | null
          title: string | null
          body: string | null
          decided_at: string
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          business_id?: string | null
          title?: string | null
          body?: string | null
          decided_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          business_id?: string | null
          title?: string | null
          body?: string | null
          decided_at?: string
          created_at?: string
        }
        Relationships: []
      }
      workspace_settings: {
        Row: { workspace_id: string; ai_provider: string | null; ai_api_key: string | null; created_at: string }
        Insert: { workspace_id: string; ai_provider?: string | null; ai_api_key?: string | null; created_at?: string }
        Update: { workspace_id?: string; ai_provider?: string | null; ai_api_key?: string | null; created_at?: string }
        Relationships: []
      }
      briefs: {
        Row: { id: string; workspace_id: string; content: string | null; for_date: string | null; created_at: string }
        Insert: { id?: string; workspace_id: string; content?: string | null; for_date?: string | null; created_at?: string }
        Update: { id?: string; workspace_id?: string; content?: string | null; for_date?: string | null; created_at?: string }
        Relationships: []
      }
      agents: {
        Row: {
          id: string
          workspace_id: string
          name: string | null
          system_prompt: string | null
          model: string | null
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          name?: string | null
          system_prompt?: string | null
          model?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          name?: string | null
          system_prompt?: string | null
          model?: string | null
          created_at?: string
        }
        Relationships: []
      }
      agent_runs: {
        Row: {
          id: string
          workspace_id: string
          agent_id: string
          input: string | null
          output: string | null
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          agent_id: string
          input?: string | null
          output?: string | null
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          agent_id?: string
          input?: string | null
          output?: string | null
          status?: string
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
